name: newsApp
description: "newsApp"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.4
  go_router: ^17.1.0
  easy_localization: ^3.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.1
  google_fonts: ^8.0.1
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2
  readmore: ^3.0.0
  pretty_dio_logger: ^1.4.0
  loader_overlay: ^5.0.0
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh: ^2.0.0
  skeletonizer: ^2.1.2
  injectable: ^2.7.1+4
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.12.0
  build_runner: ^2.11.0


flutter_native_splash:
  image: assets/images/logo_light.png
  color: "#ffffff"

  # Dark mode
  image_dark: assets/images/logodark.png
  color_dark: "#171717"

  android: true
  ios: true
  fullscreen: true




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/langs/

  # For resolution aware images,


  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
